openapi: 3.0.0
info:
  title: Oppdateringsgresnsesnitt for SFKB
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/meastp/sfkb-api/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/meastp/sfkb-update-api-draft/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://sfkb.kartverket.no/v1
  description: Server hos Kartverket
tags:
- name: Metadata
  description: Informasjon om dataset som brukeren har tilgang til
- name: features
  description: Operasjoner på features i et bestemt dataset
paths:
  /datasets:
    get:
      tags:
      - Metadata
      summary: Hent liste over alle dataset
      description: Henter en liste over alle dataset som brukeren har lese- eller skrivetilgang til.
      operationId: getDatasets
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datasets'
        401:
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: The specified resource was not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /datasets/{datasetId}:
    get:
      tags:
      - Metadata
      summary: Hent informasjon om et bestemt dataset
      description: Henter utvidet informasjon om et bestemt dataset. Her ligger all informasjon som kommer ut i listen over dataset, og i tillegg en del ekstra informasjon som enten er unødvendig eller for tung å ha med i listen over dataset.
      parameters:
      - name: datasetId
        in: path
        description: Numeric ID of the dataset to get
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datasets'
        401:
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: The specified resource was not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /datasets/{datasetId}/features:
    get:
      tags:
      - features
      summary: Hent ut features fra et dataset
      description: Henter en liste over alle dataset som brukeren har lese- eller skrivetilgang til.
      operationId: getData
      parameters:
      - name: datasetId
        in: path
        description: Numeric ID of the dataset to get
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      - name: bbox
        in: query
        description: Bounding Box
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/BoundingBox'
      - name: $filter
        in: query
        description: Filter på egenskaper (eksempel. identifikasjon.lokalid) eller objekttype for å begrense hvilke features som hentes ut
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/vnd.kartverket.sosi+gml:
              schema:
                type: object
        401:
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: The specified resource was not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - features
      summary: Endre features i et dataset
      description: Henter en liste over alle dataset som brukeren har lese- eller skrivetilgang til.
      operationId: updateData
      parameters:
      - name: datasetId
        in: path
        description: Numeric ID of the dataset to get
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
      requestBody:
        description: Optional description in *Markdown*
        content:
          application/vnd.kartverket.sosi+gml:
            schema:
              type: object
        required: true
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: The specified resource was not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Datasets:
      type: array
      items:
        $ref: '#/components/schemas/Datasets_inner'
    BoundingBox:
      type: object
      properties:
        ll:
          type: number
          format: double
        ur:
          type: number
          format: double
    Error:
      required:
      - title
      - type
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
    Datasets_inner:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        kommune:
          type: integer
          format: int32
        fylke:
          type: integer
          format: int32
        sone:
          type: integer
          format: int32
        resolution:
          type: number
          format: double
        coordinate_reference_system:
          type: string
        read_only:
          type: boolean
        bbox:
          $ref: '#/components/schemas/BoundingBox'
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
